// MIK97 Release Engine types
// Re-exported from backend for convenience. ReleaseAuditEntry and ReleaseEngineConfig
// are the canonical types generated by bindgen from the Motoko actor.
export type {
  ReleaseAuditEntry,
  ReleaseEngineConfig,
} from "../backend";

export interface EmissionStats {
  dailyReleasedToday: bigint;
  weeklyReleasedThisWeek: bigint;
  maxDailyRelease: bigint;
  maxWeeklyRelease: bigint;
  isPaused: boolean;
  rewardPoolPercent: bigint;
}

/**
 * Dynamic ratio configuration for MIK97 discount/reward scaling.
 * When isEnabled = false (pre-exchange), all discounts use the fixed
 * 100 MIK97 = $1 rate. When enabled, tokenPriceUsd drives the ratio.
 */
export interface DynamicRatioConfig {
  isEnabled: boolean;
  tokenPriceUsd: number;
  priceLastUpdated: bigint;
  discountMode: "Fixed" | "Dynamic";
  /** Global reward mode: Fixed = all sections use token amounts; Dynamic = sections use USD target values */
  rewardMode: "Fixed" | "Dynamic";
  /** Per-section reward mode overrides */
  perSectionRewardMode: PerSectionRewardMode;
  /** Dollar value target per section when in dynamic reward mode */
  dollarValueConfig: DollarValueConfig;
  /** Price source: manual or live (live is post-exchange-listing only) */
  priceSource: "manual" | "live";
}

/** Pool detail returned by getPoolDetails */
export interface PoolDetail {
  poolName: string;
  allocated: number;
  released: number;
  locked: number;
  burned: number;
  currentBalance: number;
}

/** Audit log entry returned by getReleaseAuditLogV2 */
export interface ReleaseAuditEntryV2 {
  id: string;
  timestamp: bigint;
  amount: number;
  poolName: string;
  reason: string;
  triggeredBy: string;
  success: boolean;
  errorMsg: string | null;
}

/** Release schedule returned by listReleaseSchedules */
export interface ReleaseSchedule {
  scheduleId: string;
  poolName: string;
  amountPerCycle: number;
  interval: string;
  nextRunTime: bigint;
  isPaused: boolean;
  createdAt: bigint;
}

/** Pool activity log entry from getPoolActivityLog */
export interface PoolActivityEntry {
  pool: string;
  action: string;
  initiator: string;
  amount: number;
  timestamp: number;
}

/** Full transaction ledger entry — extends PoolActivityEntry with extra fields */
export interface TransactionLedgerEntry extends PoolActivityEntry {
  txId: number;
  txType: "admin_action" | "user_action" | "system_action" | "legacy";
  rewardsEarned: number;
}

/** Filters for the transaction ledger panel */
export interface TransactionLedgerFilters {
  searchQuery: string;
  txTypeFilter: "all" | "admin_action" | "user_action" | "system_action";
  poolFilter: string;
  startDate: string;
  endDate: string;
}

// ── Dynamic Ratio Extended Types ────────────────────────────────────────────

/** Per-section reward mode: Fixed (fixed token amount) or Dynamic (dollar-value-based) */
export type SectionRewardMode = "Fixed" | "Dynamic";

/** Reward mode setting per section */
export type PerSectionRewardMode = Record<string, SectionRewardMode>;

/** Dollar value target per section (what each action is worth in USD) */
export type DollarValueConfig = Record<string, number>;

/** Live preview entry for a single reward section */
export interface DynamicRewardPreviewEntry {
  sectionName: string;
  currentMode: SectionRewardMode;
  usdValue: number;
  tokenPayout: number;
  tokenPriceUsd: number;
}

// ── Liquidity Deployment Types ───────────────────────────────────────────────

/** A single deployment log entry */
export interface LiquidityDeploymentLogEntry {
  id: string;
  amount: number;
  timestamp: bigint;
  destinationNote: string;
  deployedBy: string;
}

/** Per-section reward pause toggles */
export interface RewardSectionToggles {
  gameRewardsEnabled: boolean;
  flappyRewardsEnabled: boolean;
  musicRewardsEnabled: boolean;
  liveRewardsEnabled: boolean;
  showcaseRewardsEnabled: boolean;
  mixtapeRewardsEnabled: boolean;
  forumRewardsEnabled: boolean;
  bonusActionsEnabled: boolean;
}

/** Forum reward configuration */
export interface ForumRewardConfig {
  tokensPerMessage: number;
  dailyEarningCap: number;
  rewardEveryNMessages: bigint;
  isEnabled: boolean;
}
