/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'pageVisits' : PageVisits,
  'dailyVisits' : Array<DailyVisit>,
  'totalVisits' : bigint,
  'uniqueVisitors' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AudioFileEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'fileType' : AudioFileType,
}
export type AudioFileType = { 'mp3' : null } |
  { 'wav' : null } |
  { 'stems' : null };
export interface Beat {
  'id' : string,
  'title' : string,
  'preview' : PreviewEntry,
  'deliveryMethod' : DeliveryMethod,
  'rightsFolders' : Array<RightsFolder>,
  'style' : BeatStyle,
  'approved' : boolean,
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artist' : string,
  'coverArt' : Array<CoverArtEntry>,
}
export type BeatCategory = { 'pop' : null } |
  { 'lofi' : null } |
  { 'rock' : null } |
  { 'hipHop' : null } |
  { 'electronic' : null };
export interface BeatFilter {
  'style' : [] | [BeatStyle],
  'texture' : [] | [BeatTexture],
  'category' : [] | [BeatCategory],
}
export type BeatStyle = { 'experimental' : null } |
  { 'oldSchool' : null } |
  { 'trap' : null } |
  { 'classic' : null } |
  { 'modern' : null } |
  { 'jazzInfluence' : null };
export type BeatTexture = { 'smooth' : null } |
  { 'gritty' : null } |
  { 'upbeat' : null } |
  { 'melodic' : null };
export interface BeatTierDiscountConfig {
  'stemsMaxDiscountPercent' : number,
  'basicMaxDiscountPercent' : number,
  'premiumDiscountEnabled' : boolean,
  'stemsDiscountEnabled' : boolean,
  'exclusiveDiscountEnabled' : boolean,
  'basicDiscountEnabled' : boolean,
  'premiumMaxDiscountPercent' : number,
  'exclusiveMaxDiscountPercent' : number,
}
export interface BonusEarningConfig {
  'purchaseCashbackPercent' : number,
  'mixtapeUploadRewardEnabled' : boolean,
  'showcaseUploadRewardEnabled' : boolean,
  'streakTarget' : bigint,
  'loginBonusTokens' : number,
  'showcaseUploadBonusTokens' : number,
  'streakBonusTokens' : number,
}
export interface BurnEventPublic {
  'id' : string,
  'user' : Principal,
  'useCase' : string,
  'beatId' : [] | [string],
  'timestamp' : bigint,
  'amount' : number,
}
export interface CoverArtEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'fileType' : CoverArtType,
}
export type CoverArtType = { 'jpg' : null } |
  { 'png' : null } |
  { 'webp' : null };
export interface DailyCapConfig {
  'musicCap' : number,
  'totalDailyCapAcrossAll' : number,
  'showcaseCap' : number,
  'bonusCap' : number,
  'liveCap' : number,
  'gamesCap' : number,
}
export interface DailyCapStatus {
  'musicCap' : number,
  'liveEarned' : number,
  'lastReset' : bigint,
  'gamesEarned' : number,
  'liveCap' : number,
  'musicEarned' : number,
  'gamesCap' : number,
}
export interface DailyEarningsByCategory {
  'jumperEarned' : number,
  'flappyEarned' : number,
  'liveEarned' : number,
  'lastReset' : bigint,
  'forumEarned' : number,
  'mixtapeEarned' : number,
  'showcaseEarned' : number,
  'musicEarned' : number,
  'bonusEarned' : number,
}
export interface DailyVisit { 'date' : string, 'count' : bigint }
export type DeliveryMethod = { 'googleDrive' : null } |
  { 'zipFiles' : null };
export type DiscountMode = { 'Dynamic' : null } |
  { 'Fixed' : null };
export interface DollarValueConfig {
  'showcaseUsdValue' : number,
  'mixtapeUsdValue' : number,
  'musicUsdValue' : number,
  'bonusUsdValue' : number,
  'forumUsdValue' : number,
  'liveUsdValue' : number,
  'gamesUsdValue' : number,
}
export interface DynamicRatioConfig {
  'tokenPriceUsd' : number,
  'discountMode' : DiscountMode,
  'priceLastUpdated' : bigint,
  'isEnabled' : boolean,
  'rewardMode' : RewardMode,
  'perSectionRewardMode' : PerSectionRewardMode,
  'dollarValueConfig' : DollarValueConfig,
}
export type EarnCategory = { 'music' : null } |
  { 'live' : null } |
  { 'games' : null } |
  { 'bonus' : null };
export interface EarnEntryPublic {
  'description' : string,
  'timestamp' : bigint,
  'category' : EarnCategory,
  'amount' : number,
}
export interface EarnResult {
  'capReached' : boolean,
  'dailyEarned' : number,
  'tokensEarned' : number,
  'newBalance' : number,
  'dailyCap' : number,
}
export type ExternalBlob = Uint8Array;
export interface ForumRewardConfig {
  'tokensPerMessage' : number,
  'isEnabled' : boolean,
  'rewardEveryNMessages' : bigint,
  'dailyEarningCap' : number,
}
export interface GameScore {
  'displayName' : string,
  'player' : Principal,
  'score' : bigint,
  'timestamp' : bigint,
  'gameType' : string,
}
export interface ICRC1Token {
  'fee' : bigint,
  'initialCirculating' : bigint,
  'decimals' : number,
  'logo' : string,
  'name' : string,
  'totalSupply' : bigint,
  'symbol' : string,
}
export interface LicenseDocEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'docType' : LicenseDocType,
}
export type LicenseDocType = { 'pdf' : null } |
  { 'txt' : null } |
  { 'docx' : null } |
  { 'folder' : null };
export interface LiquidityDeploymentEntry {
  'deployedBy' : string,
  'destinationNote' : string,
  'entryId' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface LiveStream {
  'id' : string,
  'title' : string,
  'host' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface MIK97TokenSupply {
  'initialCirculating' : bigint,
  'expansionReserve' : TreasuryPool,
  'totalBoughtBack' : bigint,
  'liquidityPool' : TreasuryPool,
  'promotionsPool' : TreasuryPool,
  'currentCirculating' : bigint,
  'totalBurned' : bigint,
  'reservePool' : TreasuryPool,
  'totalMaxSupply' : bigint,
  'teamPayoutReserve' : bigint,
  'platformTeamPool' : TreasuryPool,
  'rewardsPool' : TreasuryPool,
  'adminPersonalAllocation' : bigint,
}
export interface Message {
  'id' : string,
  'principal' : Principal,
  'createdAt' : bigint,
  'authorName' : [] | [string],
  'sectionId' : string,
  'message' : string,
}
export interface MessageUpdate { 'id' : string, 'updatedContent' : string }
export interface MigrationLogEntry {
  'totalTokensDistributed' : bigint,
  'triggeredBy' : Principal,
  'timestamp' : bigint,
  'totalUsers' : bigint,
}
export interface Milestone {
  'media' : [] | [ExternalBlob],
  'title' : string,
  'order' : bigint,
  'date' : string,
  'description' : string,
}
export interface Mixtape {
  'id' : string,
  'title' : string,
  'externalLinks' : Array<string>,
  'description' : string,
  'songs' : Array<ExternalBlob>,
  'approved' : boolean,
  'uploader' : Principal,
  'artistName' : string,
  'coverArt' : [] | [ExternalBlob],
}
export interface MixtapeRewardConfig {
  'tier3Tokens' : number,
  'tier4Tokens' : number,
  'dailyCap' : number,
  'tier1Tokens' : number,
  'tier2Tokens' : number,
}
export interface MixtapeSubmissionFeeConfig {
  'enabled' : boolean,
  'priceInCents' : bigint,
}
export interface MusicLink {
  'url' : string,
  'title' : string,
  'platform' : Platform,
  'coverArt' : [] | [ExternalBlob],
  'releaseDate' : [] | [string],
}
export type PageType = { 'mva' : null } |
  { 'forum' : null } |
  { 'live' : null } |
  { 'mixtapes' : null } |
  { 'store' : null } |
  { 'musicLinks' : null } |
  { 'showcase' : null };
export interface PageVisits {
  'mva' : bigint,
  'forum' : bigint,
  'live' : bigint,
  'mixtapes' : bigint,
  'store' : bigint,
  'musicLinks' : bigint,
  'showcase' : bigint,
}
export interface PerSectionRewardMode {
  'forum' : RewardMode,
  'music' : RewardMode,
  'mixtape' : RewardMode,
  'live' : RewardMode,
  'games' : RewardMode,
  'bonus' : RewardMode,
  'showcase' : RewardMode,
}
export type Platform = { 'soundcloud' : null } |
  { 'other' : string } |
  { 'spotify' : null } |
  { 'youtube' : null } |
  { 'appleMusic' : null };
export interface PlatformToggles {
  'gamesMode' : VisibilityMode,
  'showPublicLedger' : boolean,
  'walletMode' : VisibilityMode,
  'showHeaderCoinBalance' : boolean,
}
export type PoLBadgeTier = { 'Gold' : null } |
  { 'Bronze' : null } |
  { 'Silver' : null };
export interface PoLConfig {
  'polEnabled' : boolean,
  'polMinConfidenceThreshold' : bigint,
  'silverMin' : bigint,
  'polRewardMultiplier' : number,
  'goldMin' : bigint,
  'bronzeMin' : bigint,
}
export interface PoLResetConfig {
  'resetTimeOfDayHours' : bigint,
  'resetIntervalDays' : bigint,
  'resetEnabled' : boolean,
}
export interface PoLSessionRecord {
  'startTime' : bigint,
  'contentId' : string,
  'contentType' : string,
  'endTime' : bigint,
  'playbackDurationMs' : bigint,
  'confidenceScore' : number,
  'tabActivityScore' : number,
  'earnedTokens' : number,
  'playbackContinuityScore' : number,
  'sessionId' : string,
  'badgeAwarded' : [] | [PoLBadgeTier],
}
export interface PoSPConfig {
  'autoRoomPlayCountThreshold' : bigint,
  'consensusWindowMinutes' : bigint,
  'minActiveTimePercent' : bigint,
  'nativeRewardRatePerMinute' : bigint,
  'autoRoomEnabled' : boolean,
  'defaultRoomCapacity' : bigint,
  'layer2Enabled' : boolean,
  'hostFeeAmount' : bigint,
  'externalRewardRatePerMinute' : bigint,
  'maxScheduledRoomsPerDay' : bigint,
  'defaultRoomDurationMinutes' : bigint,
  'hostFeeEnabled' : boolean,
  'minGroupSize' : bigint,
}
export interface PoSPParticipantSession {
  'verified' : boolean,
  'interactionChecksFailed' : bigint,
  'interactionChecksPassed' : bigint,
  'rewardClaimed' : boolean,
  'lastActiveAt' : bigint,
  'joinedAt' : bigint,
  'presenceScore' : bigint,
  'participant' : Principal,
  'roomId' : string,
  'rewardEarned' : bigint,
}
export interface PoSPRoom {
  'id' : string,
  'status' : PoSPRoomStatus,
  'title' : string,
  'expiresAt' : bigint,
  'contentType' : PoSPRoomType,
  'currentParticipants' : Array<Principal>,
  'contentUrl' : string,
  'createdAt' : bigint,
  'sessionConfidenceScore' : bigint,
  'totalRewardPaid' : bigint,
  'hostFeePaid' : bigint,
  'hostPrincipal' : Principal,
  'durationMinutes' : bigint,
  'isAutoRoom' : boolean,
  'capacity' : bigint,
  'scheduledAt' : [] | [bigint],
}
export type PoSPRoomStatus = { 'Active' : null } |
  { 'Waiting' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Expired' : null };
export type PoSPRoomType = { 'SonicHash' : null } |
  { 'PresenceTracking' : null };
export interface PoolActivityEntry {
  'action' : string,
  'initiator' : string,
  'pool' : string,
  'txId' : bigint,
  'rewardsEarned' : number,
  'timestamp' : bigint,
  'txType' : string,
  'amount' : number,
}
export interface PreviewEntry {
  'duration' : bigint,
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'previewType' : PreviewType,
}
export type PreviewType = { 'audio' : null } |
  { 'video' : null };
export interface ReleaseAuditEntry {
  'triggeredBy' : string,
  'timestamp' : bigint,
  'poolName' : string,
  'amount' : bigint,
  'reason' : ReleaseReason,
}
export interface ReleaseAuditEntryView {
  'triggeredBy' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'poolName' : string,
  'amount' : number,
  'errorMsg' : [] | [string],
  'reason' : string,
}
export interface ReleaseEngineConfig {
  'autoReleasePaused' : boolean,
  'isPaused' : boolean,
  'autoReleaseEnabled' : boolean,
  'maxDailyReleaseTokens' : bigint,
  'scheduledReleaseAmountPerPool' : bigint,
  'rewardPoolThresholdPercent' : bigint,
  'maxWeeklyReleaseTokens' : bigint,
}
export type ReleaseInterval = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type ReleaseReason = { 'adminManual' : null } |
  { 'scheduledRelease' : null } |
  { 'emergency' : null } |
  { 'rewardPoolLow' : null };
export interface Replay {
  'replayUrl' : string,
  'title' : string,
  'description' : string,
}
export type RewardMode = { 'Dynamic' : null } |
  { 'Fixed' : null };
export interface RewardRateConfig {
  'fiveDayCooldownNs' : bigint,
  'jumperTokensPerThreshold' : number,
  'musicTrackCompletionTokens' : number,
  'flappyTokensPerThreshold' : number,
  'liveWatchMilestones' : Array<[bigint, number]>,
  'musicAlbumCompletionTokens' : number,
  'flappyRatio' : number,
  'jumperRatio' : number,
  'musicListeningSeconds' : bigint,
  'musicListeningTokensPerInterval' : number,
}
export interface RewardSectionToggles {
  'flappyRewardsEnabled' : boolean,
  'forumRewardsEnabled' : boolean,
  'bonusActionsEnabled' : boolean,
  'liveRewardsEnabled' : boolean,
  'mixtapeRewardsEnabled' : boolean,
  'showcaseRewardsEnabled' : boolean,
  'gameRewardsEnabled' : boolean,
  'musicRewardsEnabled' : boolean,
}
export interface RightsFolder {
  'freeDownload' : boolean,
  'sold' : boolean,
  'googleDriveLink' : [] | [string],
  'zipFile' : [] | [ExternalBlob],
  'licenseDocs' : Array<LicenseDocEntry>,
  'audioFiles' : Array<AudioFileEntry>,
  'priceInCents' : bigint,
  'rightsType' : RightsType,
}
export type RightsType = { 'basicRight' : null } |
  { 'premiumRight' : null } |
  { 'exclusiveRight' : null } |
  { 'stems' : null };
export interface ScheduledRelease {
  'interval' : ReleaseInterval,
  'scheduleId' : string,
  'isPaused' : boolean,
  'createdAt' : bigint,
  'sourcePool' : [] | [string],
  'nextRunTime' : bigint,
  'poolName' : string,
  'amountPerCycle' : bigint,
}
export interface Section {
  'id' : string,
  'title' : string,
  'creator' : string,
  'createdAt' : bigint,
  'description' : string,
  'creatorName' : string,
  'linkSharingEnabled' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Show {
  'title' : string,
  'date' : string,
  'time' : string,
  'description' : string,
}
export interface Showcase {
  'id' : string,
  'externalLink' : [] | [string],
  'songName' : string,
  'audioFile' : ExternalBlob,
  'style' : BeatStyle,
  'approved' : boolean,
  'beatId' : [] | [string],
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artistName' : string,
  'coverArt' : [] | [ExternalBlob],
}
export interface ShowcaseHighlight {
  'mixtapeId' : string,
  'highlightedSong' : ExternalBlob,
  'artistName' : string,
}
export interface SpendEntryPublic {
  'useCase' : SpendUseCase,
  'beatId' : [] | [string],
  'timestamp' : bigint,
  'amount' : number,
}
export type SpendUseCase = { 'mixtapeDrop' : null } |
  { 'premiumContent' : null } |
  { 'showcaseEntry' : null } |
  { 'beatDiscount' : null };
export interface StakeRecord {
  'id' : string,
  'startTime' : bigint,
  'lockEndTime' : bigint,
  'apyAtStake' : number,
  'amountStaked' : bigint,
  'owner' : Principal,
  'isActive' : boolean,
  'rewardsClaimed' : bigint,
  'lockDays' : bigint,
}
export interface StakeResult {
  'apy' : number,
  'stakeId' : string,
  'lockEndTime' : bigint,
  'amountStaked' : number,
  'lockDays' : bigint,
  'entryFee' : number,
}
export interface StakingConfig {
  'earlyUnstakePenaltyEnabled' : boolean,
  'tier1Apy' : number,
  'tier2Apy' : number,
  'tier3Apy' : number,
  'earlyUnstakePenaltyBurnPct' : number,
  'maxStake' : number,
  'minStake' : number,
  'isEnabled' : boolean,
  'earlyUnstakePenaltyRewardsPct' : number,
  'earlyUnstakePenaltyReservePct' : number,
  'entryFeePercent' : number,
  'entryFeeEnabled' : boolean,
  'earlyUnstakePenaltyPromoPct' : number,
  'earlyUnstakePenaltyPercent' : number,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TreasuryPool {
  'totalAllocated' : bigint,
  'name' : string,
  'locked' : bigint,
  'released' : bigint,
  'burned' : bigint,
}
export interface UnstakeResult {
  'penaltyCharged' : number,
  'penaltyBurned' : number,
  'penaltyToRewards' : number,
  'principalReturned' : number,
  'rewardsPaid' : number,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'isCreator' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWalletPublic {
  'lastLoginDate' : bigint,
  'balance' : number,
  'rewardEligible' : boolean,
  'lastStreakReset' : bigint,
  'loginStreak' : bigint,
  'earnHistory' : Array<EarnEntryPublic>,
  'spendHistory' : Array<SpendEntryPublic>,
}
export interface VerifiedListenerBadge {
  'dateEarned' : bigint,
  'tier' : PoLBadgeTier,
  'isActive' : boolean,
  'confidenceScore' : number,
}
export type VisibilityMode = { 'live' : null } |
  { 'hidden' : null } |
  { 'comingSoon' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExcludedVisitor' : ActorMethod<[Principal], undefined>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'addMusicLink' : ActorMethod<
    [string, Platform, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'addReplay' : ActorMethod<[string, string, string, string], undefined>,
  'addUpcomingShow' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'airdropFromPromotions' : ActorMethod<
    [Array<[string, number]>],
    { 'ok' : Array<[string, string]> } |
      { 'err' : string }
  >,
  'applyTokenDiscount' : ActorMethod<
    [number, bigint, string, [] | [string], string],
    {
        'ok' : {
          'discountApplied' : bigint,
          'tokensActuallyBurned' : number,
          'remainingBalance' : number,
        }
      } |
      { 'err' : string }
  >,
  'approveAllShowcases' : ActorMethod<[], undefined>,
  'approveMixtape' : ActorMethod<[string], undefined>,
  'approveShowcase' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateMessages' : ActorMethod<[Array<MessageUpdate>], undefined>,
  'burnTokens' : ActorMethod<
    [number, string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'canGetBasicRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetExclusiveRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetPremiumRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetStemsRightsWithLicense' : ActorMethod<[string], boolean>,
  /**
   * / Admin-only: cancel a room.
   */
  'cancelRoom' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'checkAndAutoRelease' : ActorMethod<
    [],
    { 'ok' : [] | [ReleaseAuditEntry] } |
      { 'err' : string }
  >,
  /**
   * / Public entry point to expire rooms (can also be called by frontend or cron).
   */
  'checkAndExpireRooms' : ActorMethod<[], undefined>,
  'claimDailyLoginBonus' : ActorMethod<
    [],
    {
        'ok' : {
          'streak' : bigint,
          'tokensEarned' : number,
          'streakBonusEarned' : boolean,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: claim the full adminPersonalAllocation (5M MIK97) to a destination wallet.
   * / Can only be called once. Sets adminPersonalAllocation to 0 after claim.
   */
  'claimPersonalAllocation' : ActorMethod<
    [Principal],
    { 'ok' : { 'destination' : Principal, 'amountClaimed' : number } } |
      { 'err' : string }
  >,
  /**
   * / Claim reward after a room is completed. Validates presence threshold.
   */
  'claimRoomReward' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Claim accrued staking rewards without unstaking.
   */
  'claimStakingRewards' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  'clearFeaturedBeat' : ActorMethod<[], undefined>,
  'clearRedirectUrl' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrGetWallet' : ActorMethod<
    [],
    { 'ok' : UserWalletPublic } |
      { 'err' : string }
  >,
  /**
   * / Create a presence-tracking room (external links). Host fee deducted if enabled.
   */
  'createPresenceRoom' : ActorMethod<
    [string, string, bigint, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createReleaseSchedule' : ActorMethod<
    [string, string, number, ReleaseInterval, string],
    { 'ok' : ScheduledRelease } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: create a scheduled room.
   */
  'createScheduledRoom' : ActorMethod<
    [string, string, PoSPRoomType, bigint, bigint, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createSection' : ActorMethod<[string, string, string, boolean], undefined>,
  'deleteBasicRightsLicense' : ActorMethod<[], undefined>,
  'deleteBeat' : ActorMethod<[string], undefined>,
  'deleteExclusiveRightsLicense' : ActorMethod<[], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deleteMilestone' : ActorMethod<[string], undefined>,
  'deleteMixtape' : ActorMethod<[string], undefined>,
  'deleteMusicLink' : ActorMethod<[string], undefined>,
  'deleteMvaPreview' : ActorMethod<[], undefined>,
  'deletePremiumRightsLicense' : ActorMethod<[], undefined>,
  'deleteReleaseSchedule' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteReplay' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<[string], undefined>,
  'deleteShowcase' : ActorMethod<[string], undefined>,
  'deleteStemsRightsLicense' : ActorMethod<[], undefined>,
  'deleteUpcomingShow' : ActorMethod<[string], undefined>,
  'earnTokens' : ActorMethod<
    [string, bigint, [] | [string], [] | [string]],
    { 'ok' : EarnResult } |
      { 'err' : string }
  >,
  'emergencyPauseAll' : ActorMethod<
    [boolean],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'endAllLiveStreams' : ActorMethod<[], undefined>,
  'endLiveStream' : ActorMethod<[string], undefined>,
  'endLiveWatchSession' : ActorMethod<
    [],
    { 'ok' : { 'totalEarned' : number } } |
      { 'err' : string }
  >,
  /**
   * / Execute all due scheduled releases. Call this from a heartbeat or manually.
   * / Skips paused schedules and respects daily/weekly caps.
   * / autoReleasePaused only blocks the threshold-based auto-release (checkAndAutoRelease),
   * / NOT the interval-based scheduled releases created by createReleaseSchedule.
   */
  'executeScheduledReleases' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'expandPoolCeiling' : ActorMethod<
    [string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'filterBeats' : ActorMethod<[BeatFilter], Array<Beat>>,
  /**
   * / Returns current accrued (unclaimed) reward for a stake in MIK97.
   */
  'getAccruedRewards' : ActorMethod<[string], number>,
  'getActiveLiveStreams' : ActorMethod<[], Array<LiveStream>>,
  /**
   * / Returns open (Active or Waiting) rooms visible to all users.
   */
  'getActiveRooms' : ActorMethod<[], Array<PoSPRoom>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getApprovedMixtapes' : ActorMethod<[], Array<Mixtape>>,
  'getApprovedShowcases' : ActorMethod<[], Array<Showcase>>,
  'getBasicRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getBeat' : ActorMethod<[string], [] | [Beat]>,
  /**
   * / Returns per-rights-tier discount percentage caps. Public — needed at checkout.
   * / Applies safe defaults if any percentage fields are out of range.
   */
  'getBeatTierDiscountConfig' : ActorMethod<[], BeatTierDiscountConfig>,
  'getBeats' : ActorMethod<[], Array<Beat>>,
  /**
   * / Returns the current bonus earning config. Public — used by wallet/how-to-earn displays.
   * / Normalizes legacy stored value: showcaseUploadBonusTokens >= 5000 → corrected to 50.
   * / Ensures all toggle fields have safe defaults in case old stored data is missing them.
   */
  'getBonusEarningConfig' : ActorMethod<[], BonusEarningConfig>,
  'getBurnStats' : ActorMethod<
    [],
    {
      'burnByUseCase' : Array<[string, number]>,
      'totalBurned' : number,
      'recentBurns' : Array<BurnEventPublic>,
    }
  >,
  'getBurnStatsAdmin' : ActorMethod<
    [],
    {
      'burnByUseCase' : Array<[string, number]>,
      'totalBurned' : number,
      'recentBurns' : Array<BurnEventPublic>,
      'burnLogSize' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyCapConfig' : ActorMethod<[], DailyCapConfig>,
  'getDailyCapStatus' : ActorMethod<
    [],
    { 'ok' : DailyCapStatus } |
      { 'err' : string }
  >,
  'getDailyLoginStatus' : ActorMethod<
    [],
    {
      'lastLoginDate' : bigint,
      'canClaimBonus' : boolean,
      'loginStreak' : bigint,
    }
  >,
  'getDecimalFactor' : ActorMethod<[], bigint>,
  'getDynamicRatioConfig' : ActorMethod<[], DynamicRatioConfig>,
  'getDynamicRewardPreview' : ActorMethod<
    [],
    Array<
      {
        'tokenPriceUsd' : number,
        'sectionName' : string,
        'currentMode' : string,
        'tokenPayout' : number,
        'usdValue' : number,
      }
    >
  >,
  'getEmissionStats' : ActorMethod<
    [],
    {
      'activeScheduleCount' : bigint,
      'scheduledReleaseCount' : bigint,
      'rewardPoolPercent' : bigint,
      'maxDailyRelease' : bigint,
      'autoReleasePaused' : boolean,
      'isPaused' : boolean,
      'dailyReleasedToday' : bigint,
      'maxWeeklyRelease' : bigint,
      'weeklyReleasedThisWeek' : bigint,
    }
  >,
  'getExcludedVisitors' : ActorMethod<[], Array<Principal>>,
  'getExclusiveRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getFeaturedBeat' : ActorMethod<[], [] | [Beat]>,
  'getForumRewardConfig' : ActorMethod<[], ForumRewardConfig>,
  'getForumRewardsPublicInfo' : ActorMethod<
    [],
    {
      'tokensPerMessage' : number,
      'isEnabled' : boolean,
      'rewardEveryNMessages' : bigint,
    }
  >,
  'getFundingMilestone' : ActorMethod<
    [],
    {
      'reached' : boolean,
      'goal' : number,
      'isVisible' : boolean,
      'current' : number,
      'percentage' : number,
    }
  >,
  'getGameLeaderboard' : ActorMethod<[string], Array<GameScore>>,
  'getGoogleDriveLink' : ActorMethod<
    [string, RightsType, [] | [string]],
    [] | [string]
  >,
  'getICRC1Balance' : ActorMethod<[Principal], bigint>,
  'getICRC1Owner' : ActorMethod<[], [] | [Principal]>,
  'getICRC1TokenInfo' : ActorMethod<[], ICRC1Token>,
  'getICRC1TotalMinted' : ActorMethod<[], bigint>,
  'getLicenseFiles' : ActorMethod<
    [string, RightsType, [] | [string]],
    Array<ExternalBlob>
  >,
  'getLiquidityDeploymentLog' : ActorMethod<
    [],
    Array<LiquidityDeploymentEntry>
  >,
  'getLiquidityPoolStatus' : ActorMethod<
    [],
    {
      'balance' : number,
      'ceiling' : number,
      'deploymentStatus' : string,
      'percentRemaining' : number,
      'deploymentNote' : string,
      'isLocked' : boolean,
    }
  >,
  'getLiveWatchStatus' : ActorMethod<
    [],
    {
        'ok' : {
          'isInSession' : boolean,
          'tokensEarnedToday' : number,
          'canStartNew' : boolean,
          'dailyCap' : number,
          'cooldownEndsAt' : [] | [bigint],
          'minutesWatched' : bigint,
        }
      } |
      { 'err' : string }
  >,
  'getManySections' : ActorMethod<[Array<string>], Array<Section>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMigrationLog' : ActorMethod<[], Array<MigrationLogEntry>>,
  'getMilestones' : ActorMethod<[], Array<Milestone>>,
  'getMixtapeRewardConfig' : ActorMethod<[], MixtapeRewardConfig>,
  'getMixtapeSubmissionFeeConfig' : ActorMethod<[], MixtapeSubmissionFeeConfig>,
  /**
   * / Returns the Float token reward for a mixtape upload with the given song count.
   * / Public — used by the frontend to show the reward before upload.
   */
  'getMixtapeUploadReward' : ActorMethod<[bigint], number>,
  'getMusicLinks' : ActorMethod<[], Array<MusicLink>>,
  'getMusicRewardStatus' : ActorMethod<
    [string, string],
    {
      'alreadyEarned' : boolean,
      'dailyCapRemaining' : number,
      'cooldownDaysLeft' : bigint,
    }
  >,
  'getMvaPreview' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMyDailyEarnings' : ActorMethod<
    [],
    {
        'ok' : {
          'globalCapHit' : boolean,
          'breakdown' : {
            'musicCap' : number,
            'jumperEarned' : number,
            'flappyEarned' : number,
            'liveEarned' : number,
            'forumEarned' : number,
            'mixtapeEarned' : number,
            'showcaseEarned' : number,
            'jumperCap' : number,
            'gamesEarned' : number,
            'flappyCap' : number,
            'liveCap' : number,
            'musicEarned' : number,
            'gamesCap' : number,
            'bonusEarned' : number,
          },
          'globalCap' : number,
          'totalEarnedToday' : number,
          'resetInSeconds' : bigint,
          'globalCapRemaining' : number,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Returns per-category daily earning breakdown for the caller.
   * / All 8 reward categories tracked individually with caps.
   */
  'getMyDailyEarningsByCategory' : ActorMethod<
    [],
    { 'ok' : DailyEarningsByCategory } |
      { 'err' : string }
  >,
  /**
   * / Returns the caller's Verified Listener Badges (all tiers).
   */
  'getMyPoLBadges' : ActorMethod<[], Array<VerifiedListenerBadge>>,
  /**
   * / Returns the caller's recent PoL sessions, most recent first, up to `limit`.
   */
  'getMyPoLSessions' : ActorMethod<[bigint], Array<PoLSessionRecord>>,
  /**
   * / Returns the caller's PoSP participant sessions.
   */
  'getMyRoomSessions' : ActorMethod<[], Array<PoSPParticipantSession>>,
  /**
   * / Returns caller's stakes (active and closed).
   */
  'getMyStakes' : ActorMethod<[], Array<StakeRecord>>,
  /**
   * / Returns the Int timestamp (nanoseconds) of when the next PoL tier reset will fire.
   * / Returns 0 if reset is disabled.
   */
  'getNextPoLResetTime' : ActorMethod<[], bigint>,
  /**
   * / Admin query: returns the most recent 'limit' payout audit entries (max 500).
   */
  'getPayoutAuditLog' : ActorMethod<
    [bigint],
    Array<
      {
        'id' : string,
        'recipient' : string,
        'actionType' : string,
        'poolDrawnFrom' : string,
        'timestamp' : bigint,
        'category' : string,
        'amount' : number,
      }
    >
  >,
  'getPendingMixtapes' : ActorMethod<[], Array<Mixtape>>,
  'getPendingShowcases' : ActorMethod<[], Array<Showcase>>,
  /**
   * / Query: returns personal allocation status for the admin.
   */
  'getPersonalAllocationStatus' : ActorMethod<
    [],
    {
      'destination' : [] | [Principal],
      'allocated' : number,
      'claimed' : boolean,
      'claimedAt' : [] | [bigint],
    }
  >,
  'getPlatformToggles' : ActorMethod<[], PlatformToggles>,
  /**
   * / Returns current PoL configuration (readable by anyone).
   */
  'getPoLConfig' : ActorMethod<[], PoLConfig>,
  /**
   * / Returns current PoL reset configuration (readable by anyone).
   */
  'getPoLResetConfig' : ActorMethod<[], PoLResetConfig>,
  /**
   * / Returns current PoSP configuration (readable by anyone).
   */
  'getPoSPConfig' : ActorMethod<[], PoSPConfig>,
  /**
   * / Admin query: get a single room with full detail.
   */
  'getPoSPRoomDetails' : ActorMethod<
    [string],
    { 'ok' : PoSPRoom } |
      { 'err' : string }
  >,
  /**
   * / Admin query: list rooms, optionally filtered by status.
   */
  'getPoSPRooms' : ActorMethod<[[] | [PoSPRoomStatus]], Array<PoSPRoom>>,
  /**
   * / Returns aggregate Layer 2 statistics.
   */
  'getPoSPStats' : ActorMethod<
    [],
    {
      'totalRewardsPaid' : bigint,
      'totalVerifiedSessions' : bigint,
      'activeRooms' : bigint,
      'totalRooms' : bigint,
    }
  >,
  /**
   * / Admin query: returns the most recent pool activity entries (legacy compatibility).
   */
  'getPoolActivityLog' : ActorMethod<[[] | [bigint]], Array<PoolActivityEntry>>,
  /**
   * / Returns detailed stats for all treasury pools as Float values for the admin treasury panel.
   */
  'getPoolDetails' : ActorMethod<
    [],
    {
      'circulatingSupply' : number,
      'totalBoughtBack' : number,
      'totalBurned' : number,
      'teamPayoutReserve' : number,
      'pools' : Array<
        {
          'totalAllocated' : number,
          'currentBalance' : number,
          'name' : string,
          'locked' : number,
          'released' : number,
          'isExpansionReserve' : boolean,
          'poolKey' : string,
          'burned' : number,
        }
      >,
      'maxSupply' : number,
      'stakingVaultTotal' : number,
      'adminPersonalAllocation' : number,
    }
  >,
  'getPremiumRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  /**
   * / Public query: returns paginated transaction ledger for the public explorer page.
   * / Accessible by anyone (not just admins).
   */
  'getPublicTransactionLedger' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<PoolActivityEntry>
  >,
  /**
   * / Public query: total count of transaction ledger entries (for pagination).
   */
  'getPublicTransactionLedgerCount' : ActorMethod<[], bigint>,
  'getPurchaseHistory' : ActorMethod<[], Array<string>>,
  'getRedirectUrl' : ActorMethod<[], [] | [string]>,
  'getReleaseAuditLog' : ActorMethod<[], Array<ReleaseAuditEntry>>,
  /**
   * / Returns release audit log entries in the extended view format with Float amounts,
   * / human-readable reason strings, and success/errorMsg fields (always true/null for
   * / legacy entries which are all successful by definition).
   */
  'getReleaseAuditLogV2' : ActorMethod<[], Array<ReleaseAuditEntryView>>,
  'getReleaseEngineConfig' : ActorMethod<[], ReleaseEngineConfig>,
  'getReplays' : ActorMethod<[], Array<Replay>>,
  'getRewardRateConfig' : ActorMethod<[], RewardRateConfig>,
  'getRewardSectionToggles' : ActorMethod<[], RewardSectionToggles>,
  'getRightsZipFile' : ActorMethod<
    [string, RightsType, [] | [string]],
    [] | [ExternalBlob]
  >,
  /**
   * / Returns all participant sessions for a room (anyone can query).
   */
  'getRoomParticipants' : ActorMethod<[string], Array<PoSPParticipantSession>>,
  'getSection' : ActorMethod<[string], [] | [Section]>,
  'getSectionLinkSharing' : ActorMethod<[string], boolean>,
  'getSections' : ActorMethod<[], Array<Section>>,
  'getShowcaseHighlights' : ActorMethod<[], Array<ShowcaseHighlight>>,
  /**
   * / Returns current staking configuration (public query).
   */
  'getStakingConfig' : ActorMethod<[], StakingConfig>,
  'getStemsRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Admin query: returns all team payout log entries (newest first), amounts as Float.
   */
  'getTeamPayoutLog' : ActorMethod<
    [],
    Array<
      {
        'id' : string,
        'recipient' : string,
        'description' : string,
        'authorizedBy' : string,
        'timestamp' : bigint,
        'amount' : number,
      }
    >
  >,
  'getTokenSupply' : ActorMethod<[], [] | [MIK97TokenSupply]>,
  /**
   * / Admin query: full transaction ledger with filtering and pagination.
   * / actionCategory: substring match on txType ("user_action", "admin_action", "system_action")
   * /   or on action string (e.g. "burn", "stake", "earn") — matched against both fields.
   * / initiatorFilter: substring match on initiator (principal text or "system").
   * / poolFilter: exact match on pool name.
   * / startTime / endTime: inclusive timestamp bounds (nanoseconds, Time.now() scale).
   * / limit / offset: pagination.
   */
  'getTransactionLedger' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      bigint,
      bigint,
    ],
    Array<PoolActivityEntry>
  >,
  /**
   * / Admin query: count of entries matching the given filters (for pagination UI).
   */
  'getTransactionLedgerCount' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [bigint], [] | [bigint]],
    bigint
  >,
  'getUpcomingShows' : ActorMethod<[], Array<Show>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWallet' : ActorMethod<[], [] | [UserWalletPublic]>,
  'getWalletCount' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'heartbeatLiveWatch' : ActorMethod<
    [],
    {
        'ok' : {
          'tokensEarned' : number,
          'minutesWatched' : bigint,
          'nextMilestone' : [] | [bigint],
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Called when native content plays to potentially trigger an auto-room.
   */
  'incrementContentPlayCount' : ActorMethod<[string], undefined>,
  'initializeTokenSupply' : ActorMethod<
    [],
    { 'ok' : MIK97TokenSupply } |
      { 'err' : string }
  >,
  'initiateDeployment' : ActorMethod<
    [number, string],
    {
        'ok' : {
          'deployed' : number,
          'newLpBalance' : number,
          'logEntryId' : string,
        }
      } |
      { 'err' : string }
  >,
  'initiateMigration' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isExcludedVisitor' : ActorMethod<[Principal], boolean>,
  'isICRC1OwnershipRenounced' : ActorMethod<[], boolean>,
  'isMigrationCompleted' : ActorMethod<[], boolean>,
  'isMigrationPaused' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Join an active or waiting room.
   */
  'joinRoom' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Leave a room.
   */
  'leaveRoom' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listReleaseSchedules' : ActorMethod<[], Array<ScheduledRelease>>,
  'lockLiquidityPool' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'markMilestoneReached' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'pauseReleaseSchedule' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'processOutcall' : ActorMethod<[TransformationInput], TransformationOutput>,
  'recordBeatPurchase' : ActorMethod<
    [string, string, boolean, RightsType],
    undefined
  >,
  'recordMusicReward' : ActorMethod<
    [string, string, string, string, number],
    { 'ok' : bigint } |
      { 'err' : string } |
      { 'belowThreshold' : null } |
      { 'cooldown' : bigint }
  >,
  /**
   * / Record a presence heartbeat (called every ~30s by frontend while user is active).
   */
  'recordPresenceHeartbeat' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordSiteVisit' : ActorMethod<[PageType], undefined>,
  'rejectMixtape' : ActorMethod<[string], undefined>,
  /**
   * / Release tokens from the fully-locked expansion reserve into a target active pool.
   * / This does NOT increase circulating supply — tokens move from expansion reserve to
   * / the chosen pool, where they remain locked until users earn them through the emission system.
   * / IMPORTANT: This function ONLY reads from expansionReserve.locked.
   * / It NEVER touches reservePool under any circumstances.
   */
  'releaseFromExpansionReserve' : ActorMethod<
    [number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeExcludedVisitor' : ActorMethod<[Principal], undefined>,
  'renounceICRC1Ownership' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'resumeReleaseSchedule' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Run a specific schedule immediately (admin "Run Now" action).
   * / Executes the release right away regardless of nextRunTime, then advances nextRunTime.
   * / Returns a plain text success/error message — never an object.
   */
  'runScheduleNow' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMilestone' : ActorMethod<[string, Milestone], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setFeaturedBeat' : ActorMethod<[string], undefined>,
  'setFundingGoal' : ActorMethod<
    [number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin: show or hide the funding milestone banner on public pages.
   */
  'setFundingMilestoneVisible' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Legacy compatibility shims — delegate to the new mode-based setters.
   * / setGamesComingSoon(true) → #comingSoon; setGamesComingSoon(false) → #live.
   */
  'setGamesComingSoon' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin: set Games section visibility mode (#live | #comingSoon | #hidden).
   */
  'setGamesMode' : ActorMethod<
    [VisibilityMode],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setLiquidityDeploymentStatus' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setMixtapeSubmissionFeeConfig' : ActorMethod<[boolean, bigint], undefined>,
  /**
   * / Admin: set the penalty routing split for early unstakes.
   * / burnPct + rewardsPct + promoPct + reservePct MUST sum to 100.
   */
  'setPenaltyRouting' : ActorMethod<
    [number, number, number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: update PoL configuration.
   */
  'setPoLConfig' : ActorMethod<[PoLConfig], undefined>,
  /**
   * / Admin-only: update PoL tier reset schedule.
   */
  'setPoLResetConfig' : ActorMethod<[PoLResetConfig], undefined>,
  /**
   * / Admin-only: update Layer 2 PoSP configuration.
   */
  'setPoSPConfig' : ActorMethod<
    [PoSPConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setRedirectUrl' : ActorMethod<[string], undefined>,
  'setSectionLinkSharing' : ActorMethod<[string, boolean], undefined>,
  /**
   * / Admin: show or hide the MIK97 coin balance indicator in the page header for non-admins.
   */
  'setShowHeaderCoinBalance' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin: show or hide the public transaction ledger page for non-admins.
   */
  'setShowPublicLedger' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setShowcaseHighlight' : ActorMethod<
    [string, ExternalBlob, string],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWalletComingSoon' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin: set Wallet section visibility mode (#live | #comingSoon | #hidden).
   */
  'setWalletMode' : ActorMethod<
    [VisibilityMode],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Stake tokens from caller's wallet for a given lock period.
   * / lockDays must be 30, 90, or 180.
   */
  'stakeTokens' : ActorMethod<
    [number, bigint],
    { 'ok' : StakeResult } |
      { 'err' : string }
  >,
  'startLiveStream' : ActorMethod<[string, string, string, string], undefined>,
  'startLiveWatchSession' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitGameScore' : ActorMethod<
    [string, bigint],
    { 'ok' : EarnResult } |
      { 'err' : string }
  >,
  'submitMixtape' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      Array<ExternalBlob>,
      Array<string>,
      [] | [string],
    ],
    undefined
  >,
  'submitShowcase' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      [] | [string],
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [string],
    ],
    undefined
  >,
  /**
   * / Admin-only: transfer tokens from the Reserve pool into Rewards or Promotions pool.
   * / The reserve pool acts as a backup tank; tokens move between pools (not to circulation).
   * / IMPORTANT: This function ONLY reads from and deducts reservePool.locked.
   * / It NEVER touches expansionReserve under any circumstances.
   * / To release from expansion reserve, use releaseFromExpansionReserve() instead.
   */
  'transferFromReservePool' : ActorMethod<
    [string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transferICRC1Tokens' : ActorMethod<
    [Principal, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: transfer tokens from the 5M team payout reserve to a recipient's wallet.
   * / Amount is in MIK97 Float (e.g. 100.5). Recipient's internal wallet is credited.
   */
  'transferTokensTeamPayout' : ActorMethod<
    [Principal, number, string],
    { 'ok' : { 'amountPaid' : number, 'newTeamPayoutReserve' : number } } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerManualRelease' : ActorMethod<
    [string, number],
    { 'ok' : ReleaseAuditEntry } |
      { 'err' : string }
  >,
  'unlockLiquidityPool' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'unmarkRightsAsSold' : ActorMethod<[string, RightsType], undefined>,
  /**
   * / Unstake: return principal plus prorated unclaimed rewards.
   * / If unstaking before lock period ends and earlyUnstakePenaltyEnabled is true,
   * / a sliding-scale penalty is charged on the principal. The penalty is split
   * / into up to 4 routing destinations (burn, rewards, promotions, reserve)
   * / as configured by the admin via setPenaltyRouting().
   * / Returns a full UnstakeResult breakdown.
   */
  'unstake' : ActorMethod<
    [string],
    { 'ok' : UnstakeResult } |
      { 'err' : string }
  >,
  'updateBasicRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateBeat' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      Array<CoverArtEntry>,
      PreviewEntry,
      Array<RightsFolder>,
      DeliveryMethod,
    ],
    undefined
  >,
  /**
   * / Updates per-rights-tier discount configuration. Admin only.
   */
  'updateBeatTierDiscountConfig' : ActorMethod<
    [BeatTierDiscountConfig],
    { 'ok' : BeatTierDiscountConfig } |
      { 'err' : string }
  >,
  'updateBonusEarningConfig' : ActorMethod<
    [BonusEarningConfig],
    { 'ok' : BonusEarningConfig } |
      { 'err' : string }
  >,
  'updateDailyCapConfig' : ActorMethod<
    [DailyCapConfig],
    { 'ok' : DailyCapConfig } |
      { 'err' : string }
  >,
  'updateDynamicRatioConfig' : ActorMethod<
    [DynamicRatioConfig],
    { 'ok' : DynamicRatioConfig } |
      { 'err' : string }
  >,
  'updateExclusiveRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateForumRewardConfig' : ActorMethod<
    [ForumRewardConfig],
    { 'ok' : ForumRewardConfig } |
      { 'err' : string }
  >,
  'updateFundingAmount' : ActorMethod<
    [number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateMilestoneOrder' : ActorMethod<[Array<[string, bigint]>], undefined>,
  'updateMixtapeRewardConfig' : ActorMethod<
    [MixtapeRewardConfig],
    { 'ok' : MixtapeRewardConfig } |
      { 'err' : string }
  >,
  /**
   * / Dedicated setter for mixtape upload reward enabled flag (separate from tier config).
   */
  'updateMixtapeUploadRewardEnabled' : ActorMethod<
    [boolean],
    { 'ok' : BonusEarningConfig } |
      { 'err' : string }
  >,
  'updateMusicLink' : ActorMethod<
    [string, Platform, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'updatePremiumRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateReleaseEngineConfig' : ActorMethod<
    [ReleaseEngineConfig],
    { 'ok' : ReleaseEngineConfig } |
      { 'err' : string }
  >,
  'updateReplay' : ActorMethod<[string, string, string, string], undefined>,
  'updateRewardRateConfig' : ActorMethod<
    [RewardRateConfig],
    { 'ok' : RewardRateConfig } |
      { 'err' : string }
  >,
  'updateRewardSectionToggles' : ActorMethod<
    [RewardSectionToggles],
    { 'ok' : RewardSectionToggles } |
      { 'err' : string }
  >,
  /**
   * / Dedicated setter for showcase upload reward to avoid frontend type mismatch errors.
   * / Accepts tokens (Float MIK97) and enabled flag separately.
   */
  'updateShowcaseUploadReward' : ActorMethod<
    [number, boolean],
    { 'ok' : BonusEarningConfig } |
      { 'err' : string }
  >,
  /**
   * / Admin: update staking configuration.
   */
  'updateStakingConfig' : ActorMethod<[StakingConfig], undefined>,
  'updateStemsRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateUpcomingShow' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'uploadBasicRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadBeat' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      Array<CoverArtEntry>,
      PreviewEntry,
      Array<RightsFolder>,
      DeliveryMethod,
    ],
    undefined
  >,
  'uploadExclusiveRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadMvaPreview' : ActorMethod<[ExternalBlob], undefined>,
  'uploadPremiumRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadStemsRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'verifyBeatPurchase' : ActorMethod<[string, [] | [string]], boolean>,
  'verifyGuestBeatPurchase' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];